# Generated by Django 5.0.7 on 2024-07-29 13:36

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категории публикации',
                'verbose_name_plural': 'Категории публикаций',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Хэштег',
                'verbose_name_plural': 'Хэштеги',
            },
        ),
        migrations.CreateModel(
            name='PublicationStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views_count', models.PositiveIntegerField()),
                ('total_likes_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Публикации', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='date',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='reading_time',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='short_description',
        ),
        migrations.AddField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 13, 36, 17, 664631, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='publication',
            name='read_time',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(default='netu', verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='topic',
            field=models.CharField(default='netu', max_length=255, verbose_name='Названия'),
        ),
        migrations.AddField(
            model_name='publication',
            name='hashtags',
            field=models.ManyToManyField(to='journal.hashtag'),
        ),
    ]
