# Generated by Django 5.0.7 on 2024-07-29 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_publication_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 14, 5, 59, 19437, tzinfo=datetime.timezone.utc)),
        ),
    ]
