# Generated by Django 5.0.7 on 2024-07-31 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_publication_is_active_alter_publication_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='statistic',
        ),
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='journal.category'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
